# Generated by Django 3.2.9 on 2022-03-15 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0002_alter_game_hangman_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('ANIMALS', 'Animals'), ('CITIES', 'Cities'), ('MOVIES', 'Movies')], default='ANIMALS', max_length=20),
        ),
    ]
